### ISSUE TITLE
Error : bad restore file magic number

### ISSUE THREAD

**Issue by anglixue** [gqi/MRMix#1]
Hi,

I tried to install the package but got errors like below,

```
> devtools::install_local("MRMix-master.zip")
Installing package into ‘/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
* installing *source* package ‘MRMix’ ...
** R
** data
*** moving datasets to lazyload DB
Warning: file ‘BMI15_MDD18.RData’ has magic number 'RDX3'
  Use of save versions prior to 2 is deprecated
Error : bad restore file magic number (file may be corrupted) -- no data loaded
ERROR: lazydata failed for package ‘MRMix’
* removing ‘/R/x86_64-pc-linux-gnu-library/3.2/MRMix’
Error: Failed to install 'MRMix-master.zip' from local:
  (converted from warning) installation of package ‘/RtmpExLT8m/remotes327a172e97f4/MRMix-master’ had non-zero exit status
```

I have also tried other ways to install the package but none works. Do you have any solution to that?

Thanks!
Alex

**Comment by gqi** [comment]
Thank you for your interest in our package, Alex. Did you get the same error message when you install by devtools::install_github("gqi/MRMix")?

**Comment by anglixue** [comment]
Hi,
When I used devtools::install_github("gqi/MRMix"), I got

Error: Failed to install 'unknown package' from GitHub:
  SSL certificate problem: unable to get local issuer certificate

**Comment by gqi** [comment]
HI Alex, the previous file BMI15_MDD18.RData may depend on R version >=3.5. I changed the format of the file so it's version independent. Can you try installing it again?
