### ISSUE TITLE
Inquiry on the run time of MRMix()

### ISSUE THREAD

**Issue by Wanzhe-Liao** [gqi/MRMix#3]
May I ask if it is normal for me to run MRMix() in R language for three hours without any results? I have observed that the computer's memory usage is wavy. The screenshot has been attached.

![4f184f01d7a3c28d3026eee6993cd71](https://github.com/gqi/MRMix/assets/111515000/025fe34e-f53f-4ab4-b5b7-f43a4825b3e2)

**Comment by gqi** [comment]
Thanks for your interest. We normally expect MRMix to run mush faster. How many SNPs are in your dataset?

**Comment by Wanzhe-Liao** [comment]
Because it was unprocessed data, we used around 3000 SNPs (P values less than 5e-8, excluding LD) at the time, and this situation occurred

Afterward, we filtered and cleaned the data, and the number of SNPs increased to 170, at this point, the speed was acceptable. The problem has been solved now. Thank you for your attention!
